# Evaluación 2 Jorge Aragón Hernandez

In [2]:
import numpy as np

## Crear matriz

In [3]:
arrayejemplo = np.random.randint(1, 101, size=10)
print(arrayejemplo)

[ 31 100  87  42  26  98  95  28  91  55]


## Reshape

In [4]:
matriz = arrayejemplo.reshape(2, 5)
print (matriz)

[[ 31 100  87  42  26]
 [ 98  95  28  91  55]]


## Indexación
Extraer primera fila

In [5]:
primerafila = matriz[0,:]
print(primerafila)

[ 31 100  87  42  26]


Extraer última columna

In [6]:
ultimacolumna = matriz[:, -1]
print(ultimacolumna)

[26 55]


## Modificación
Modificar la ultima fila a que todos sus elementos sean cero


In [7]:
matriz[1, :] = 0
print(matriz)

[[ 31 100  87  42  26]
 [  0   0   0   0   0]]


# Operaciones básicas
Creación de arrays

In [8]:
arreglo1 = np.random.randint(1, 51, size=5)
arreglo2 = np.random.randint(1, 51, size=5)
print("Arreglo 1: ", arreglo1)
print("Arreglo 2: ", arreglo2)

Arreglo 1:  [33 46 23 11 46]
Arreglo 2:  [22 32 43 21 42]


Suma de arrays

In [10]:
suma = arreglo1 + arreglo2
print("La suma es: " ,suma)

La suma es:  [55 78 66 32 88]


Multiplicación de arrays

In [11]:
multi = arreglo1 * arreglo2
print("La multiplicación es: ", multi)

La multiplicación es:  [ 726 1472  989  231 1932]


Promedio y desviación de la suma


In [13]:
promedio_suma = np.mean(suma)
desviacion_suma = np.std(suma)

print("Promedio de la suma : ",promedio_suma)
print("Desviación de la suma : ",desviacion_suma)

Promedio de la suma :  63.8
Desviación de la suma :  19.39484467584105


Promedio y desviación de la multiplicación

In [14]:
promedio_multi = np.mean(multi)
desviacion_multi = np.std(multi)
print("Promedio de la suma : ",promedio_multi)
print("Desviación de la suma : ",desviacion_multi)

Promedio de la suma :  1070.0
Desviación de la suma :  588.8065896370387


# Operaciones lógicas

In [15]:
arraylogico = np.random.rand(20)
arraylogico[arraylogico < 0.5] = 0
arraylogico[arraylogico >= 0.5] = 1

print(arraylogico)

[0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1.]


Producto escalar

In [16]:
array1 = np.random.rand(3, 3)
array2 = np.random.rand(3, 3)
producto_escalar = np.dot(array1, array2)
print("Array 1: ", array1)
print("Array 2: ", array2)
print("Producto escalar: " , producto_escalar)

Array 1:  [[0.37179982 0.47276346 0.84807496]
 [0.01447364 0.38616323 0.35621266]
 [0.75523552 0.41762211 0.08254227]]
Array 2:  [[0.45764854 0.35417699 0.91167759]
 [0.42702316 0.85821556 0.29718659]
 [0.69984748 0.31906764 0.25315297]]
Producto escalar:  [[0.96555772 0.80800918 0.69415322]
 [0.42081901 0.45019346 0.21813412]
 [0.58173375 0.65223341 0.83353881]]


# Análisis de datos

In [20]:
arraydatos = np.random.randint(1, 21, size=(5, 4))

print(arraydatos)

[[17  8 13  3]
 [20 15 13  4]
 [ 3 14 19 13]
 [20 13  5 15]
 [11 11  3 15]]


Media

In [18]:
media = np.mean(arraydatos, axis=0)
print("Medición):", media)

Medición): [ 8.8 12.2 10.4  9.4]


Valor mínimo y máximo

In [19]:
# Máximo de fila
max_filas = np.max(arraydatos, axis=1)
# Mínimo de fila
min_filas = np.min(arraydatos, axis=1)
# Para imprimirlo hay que hacer un ciclo que nos vaya mostrando
for i in range(arraydatos.shape[0]):
    print(f"La fila es: {i + 1}, el máximo = {max_filas[i]}, el mínimo = {min_filas[i]}")

La fila es: 1, el máximo = 17, el mínimo = 6
La fila es: 2, el máximo = 15, el mínimo = 9
La fila es: 3, el máximo = 11, el mínimo = 1
La fila es: 4, el máximo = 15, el mínimo = 4
La fila es: 5, el máximo = 16, el mínimo = 5


Ordenar

In [22]:
ordenados = np.argsort(arraydatos[:, 1])
matrizordenada = arraydatos[ordenados]
print("Matriz ordenada :", matrizordenada)

Matriz ordenada : [[17  8 13  3]
 [11 11  3 15]
 [20 13  5 15]
 [ 3 14 19 13]
 [20 15 13  4]]
